/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg2;
import javax.swing.JOptionPane;
import Clases.RegistroImpresion;
import Clases.VisualizadorArbol;
import EDD.MonticuloBinario;
import Clases.Usuario;

/**
 *
 * @author Daniel Alonso y Génesis Peña
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    public EDD.Tablahash tablaUsuarios = new EDD.Tablahash(50);
    private Clases.Sistema sistema = new Clases.Sistema();
    private int relojSimulacion = 0;
    public EDD.MonticuloBinario monticulo = new EDD.MonticuloBinario(100);
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabsCola = new javax.swing.JTabbedPane();
        panelLista = new javax.swing.JPanel();
        panelGrafico = new javax.swing.JPanel();
        btnCargarCSV = new javax.swing.JButton();
        cbUsuarios = new javax.swing.JComboBox<>();
        lblReloj = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        chkPrioridad = new javax.swing.JCheckBox();
        btnLiberar = new javax.swing.JButton();
        btnGraficar = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        javax.swing.GroupLayout panelListaLayout = new javax.swing.GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        panelListaLayout.setVerticalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        tabsCola.addTab("Secuencia (Lista)", panelLista);

        panelGrafico.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        tabsCola.addTab("Estructura (Árbol)", panelGrafico);

        getContentPane().add(tabsCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 360, 260));

        btnCargarCSV.setText("Cargar Usuarios");
        btnCargarCSV.addActionListener(this::btnCargarCSVActionPerformed);
        getContentPane().add(btnCargarCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        cbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        lblReloj.setText("Tiempo: 0");
        getContentPane().add(lblReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        btnEnviar.setText("Enviar a Impresión");
        btnEnviar.addActionListener(this::btnEnviarActionPerformed);
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        chkPrioridad.setText("¿Prioritario?");
        chkPrioridad.addActionListener(this::chkPrioridadActionPerformed);
        getContentPane().add(chkPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        btnLiberar.setText("Liberar Impresora");
        btnLiberar.addActionListener(this::btnLiberarActionPerformed);
        getContentPane().add(btnLiberar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        btnGraficar.setText("Representación Gráfica");
        btnGraficar.addActionListener(this::btnGraficarActionPerformed);
        getContentPane().add(btnGraficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        btnEliminarUsuario.setText("Eliminar Usuario Seleccionado");
        btnEliminarUsuario.addActionListener(this::btnEliminarUsuarioActionPerformed);
        getContentPane().add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
    if (monticulo.getSize() > 0) { 
        // Llamamos a eliminarMin() que ya tienes
        RegistroImpresion eliminado = monticulo.eliminarMin(); 
        
        JOptionPane.showMessageDialog(this, "Imprimiendo: " + eliminado.getNombreDocumento() + 
                                      "\nUsuario: " + eliminado.getNombreUsuario());
    } else {
        JOptionPane.showMessageDialog(this, "La cola de impresión está vacía.");
    }
    }//GEN-LAST:event_btnLiberarActionPerformed

    private void btnCargarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarCSVActionPerformed
javax.swing.JFileChooser fc = new javax.swing.JFileChooser(); // Requerimiento técnico [cite: 104]
    int seleccion = fc.showOpenDialog(this);
    
    if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File archivo = fc.getSelectedFile();
        cbUsuarios.removeAllItems(); // Limpia la lista antes de cargar para evitar duplicados
        
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
            String linea;
            
            // HEMOS ELIMINADO LA LÍNEA QUE SALTABA EL ENCABEZADO
            
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",");
                if (datos.length >= 2) {
                    String nombre = datos[0].trim();
                    String prioridad = datos[1].trim();
                    
                    // Se inserta en la Tabla de Dispersión (Complejidad cercana a O(1)) [cite: 54, 84]
                    Usuario nuevo = new Usuario(nombre, prioridad);
                    tablaUsuarios.insertar(nuevo);
                    
                    cbUsuarios.addItem(nombre);
                }
            }
            JOptionPane.showMessageDialog(this, "Usuarios cargados exitosamente.");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnCargarCSVActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
if (cbUsuarios.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un usuario.");
        return;
    }

    String nombreUsuario = cbUsuarios.getSelectedItem().toString().trim();
    // Usamos 'buscar' de tu TablaHash
    Usuario userMatch = tablaUsuarios.buscarUsuario(nombreUsuario); 

    if (userMatch != null) {
        String nombreDoc = JOptionPane.showInputDialog(this, "Nombre del documento:");
        String paginasStr = JOptionPane.showInputDialog(this, "Número de páginas:");

        if (nombreDoc != null && paginasStr != null) {
            try {
                int etiquetaTiempo = relojSimulacion; 
                if (chkPrioridad.isSelected()) {
                    // Según tus clases, el atributo es 'prioridad'
                    if (userMatch.getTipoPrioridad().equalsIgnoreCase("prioridad_alta")) etiquetaTiempo -= 100;
                    else if (userMatch.getTipoPrioridad().equalsIgnoreCase("prioridad_media")) etiquetaTiempo -= 50;
                }

                // Creamos el registro con TUS parámetros
                RegistroImpresion nuevoDoc = new RegistroImpresion(nombreDoc, nombreUsuario, etiquetaTiempo);
                
                // Lo insertamos en TU montículo
                monticulo.insertar(nuevoDoc); 

                relojSimulacion++; 
                JOptionPane.showMessageDialog(this, "Documento enviado a la cola. Total en cola: " + monticulo.getSize());
                
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error: Las páginas deben ser un número.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Error: Usuario no encontrado.");
    }
    relojSimulacion++; 
    lblReloj.setText("Tiempo actual: " + relojSimulacion);
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void chkPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPrioridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPrioridadActionPerformed

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
if (monticulo.getSize() > 0) {
        // Usamos tu clase VisualizadorArbol
        VisualizadorArbol v = new VisualizadorArbol();
        // Le pasamos tu arreglo 'heap' y tu tamaño 'n'
        v.mostrar((Clases.RegistroImpresion[]) monticulo.getArreglo(), monticulo.getSize() + 1); 
    } else {
        JOptionPane.showMessageDialog(this, "No hay nada para graficar.");
    }
    }//GEN-LAST:event_btnGraficarActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
// 1. Obtenemos el nombre del usuario seleccionado en tu ComboBox
    String nombre = cbUsuarios.getSelectedItem().toString(); 
    
    if (nombre != null && !nombre.isEmpty()) {
        // Confirmación para evitar borrados accidentales (Usabilidad)
        int respuesta = JOptionPane.showConfirmDialog(this, 
            "¿Seguro que deseas eliminar al usuario " + nombre + "?\n" +
            "Sus documentos en cola de impresión NO serán borrados.", 
            "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        
        if (respuesta == JOptionPane.YES_OPTION) {
            // 2. Llamamos al método de la Tabla Hash que ya arreglamos
            tablaUsuarios.eliminarUsuario(nombre); 
            
            // 3. Actualizamos el ComboBox para que el usuario ya no aparezca
            cbUsuarios.removeItem(nombre);
            
            JOptionPane.showMessageDialog(this, "Usuario eliminado exitosamente.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un usuario de la lista.");
    }
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }
    public void actualizarComboUsuarios() {
        cbUsuarios.removeAllItems(); 
        cbUsuarios.addItem("Seleccione un usuario...");
        
        // Verificamos que la tabla exista
        if (this.tablaUsuarios != null) {
            String[] nombres = this.tablaUsuarios.obtenerNombresUsuarios();
            
            for (int i = 0; i < nombres.length; i++) {
                if (nombres[i] != null) { 
                    cbUsuarios.addItem(nombres[i]);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarCSV;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JComboBox<String> cbUsuarios;
    private javax.swing.JCheckBox chkPrioridad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JPanel panelGrafico;
    private javax.swing.JPanel panelLista;
    private javax.swing.JTabbedPane tabsCola;
    // End of variables declaration//GEN-END:variables
}
