/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg2;

/**
 *
 * @author Daniel Alonso
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    public EDD.Tablahash tablaUsuarios = new EDD.Tablahash(50);
    private Clases.Sistema sistema = new Clases.Sistema();
    private int relojSimulacion = 0;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabsCola = new javax.swing.JTabbedPane();
        panelLista = new javax.swing.JPanel();
        panelGrafico = new javax.swing.JPanel();
        btnCargarCSV = new javax.swing.JButton();
        cbUsuarios = new javax.swing.JComboBox<>();
        lblReloj = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        chkPrioridad = new javax.swing.JCheckBox();
        btnLiberar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        javax.swing.GroupLayout panelListaLayout = new javax.swing.GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        panelListaLayout.setVerticalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        tabsCola.addTab("Secuencia (Lista)", panelLista);

        panelGrafico.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        tabsCola.addTab("Estructura (Árbol)", panelGrafico);

        getContentPane().add(tabsCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 360, 260));

        btnCargarCSV.setText("Cargar Usuarios");
        btnCargarCSV.addActionListener(this::btnCargarCSVActionPerformed);
        getContentPane().add(btnCargarCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        cbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        lblReloj.setText("Tiempo: 0");
        getContentPane().add(lblReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        btnEnviar.setText("Enviar a Impresión");
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        chkPrioridad.setText("¿Prioritario?");
        getContentPane().add(chkPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        btnLiberar.setText("Liberar Impresora");
        btnLiberar.addActionListener(this::btnLiberarActionPerformed);
        getContentPane().add(btnLiberar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLiberarActionPerformed

    private void btnCargarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarCSVActionPerformed
        Clases.LectorCSV lector = new Clases.LectorCSV();
        
        lector.cargarUsuarios(this.tablaUsuarios);
        
        actualizarComboUsuarios();
        
        javax.swing.JOptionPane.showMessageDialog(this, "¡Usuarios cargados correctamente!");
    }//GEN-LAST:event_btnCargarCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }
    public void actualizarComboUsuarios() {
        cbUsuarios.removeAllItems(); 
        cbUsuarios.addItem("Seleccione un usuario...");
        
        // Verificamos que la tabla exista
        if (this.tablaUsuarios != null) {
            String[] nombres = this.tablaUsuarios.obtenerNombresUsuarios();
            
            for (int i = 0; i < nombres.length; i++) {
                if (nombres[i] != null) { 
                    cbUsuarios.addItem(nombres[i]);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarCSV;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JComboBox<String> cbUsuarios;
    private javax.swing.JCheckBox chkPrioridad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JPanel panelGrafico;
    private javax.swing.JPanel panelLista;
    private javax.swing.JTabbedPane tabsCola;
    // End of variables declaration//GEN-END:variables
}
